//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictogramUpdater {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PictogramUpdater.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details are valid..
        /// </summary>
        internal static string accountDetailsValid {
            get {
                return ResourceManager.GetString("accountDetailsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update application needs to be run with administrator rights. Windows will now ask you to allow this..
        /// </summary>
        internal static string adminRightsNotice {
            get {
                return ResourceManager.GetString("adminRightsNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative rights.
        /// </summary>
        internal static string adminRightsTitle {
            get {
                return ResourceManager.GetString("adminRightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start application.
        /// </summary>
        internal static string canNotStart {
            get {
                return ResourceManager.GetString("canNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update for Pictogram 4.0.
        /// </summary>
        internal static string cdHeader {
            get {
                return ResourceManager.GetString("cdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying account details....
        /// </summary>
        internal static string checkingAccountDetails {
            get {
                return ResourceManager.GetString("checkingAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server..
        /// </summary>
        internal static string couldNotConnectToServer {
            get {
                return ResourceManager.GetString("couldNotConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new directory.
        /// </summary>
        internal static string creatingNewDirectory {
            get {
                return ResourceManager.GetString("creatingNewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.4.0.8.
        /// </summary>
        internal static string currentVersion {
            get {
                return ResourceManager.GetString("currentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictogram Update.
        /// </summary>
        internal static string dialogExitTitle {
            get {
                return ResourceManager.GetString("dialogExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete. Exit update application?.
        /// </summary>
        internal static string dialogInstallationCompleteExit {
            get {
                return ResourceManager.GetString("dialogInstallationCompleteExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download aborted.
        /// </summary>
        internal static string downloadAborted {
            get {
                return ResourceManager.GetString("downloadAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete..
        /// </summary>
        internal static string downloadComplete {
            get {
                return ResourceManager.GetString("downloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string downloadingFile {
            get {
                return ResourceManager.GetString("downloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading languages....
        /// </summary>
        internal static string downloadingLanguages {
            get {
                return ResourceManager.GetString("downloadingLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading plain text images complete..
        /// </summary>
        internal static string downloadPlainTextComplete {
            get {
                return ResourceManager.GetString("downloadPlainTextComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound download complete.
        /// </summary>
        internal static string downloadSoundsComplete {
            get {
                return ResourceManager.GetString("downloadSoundsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading images without text complete..
        /// </summary>
        internal static string downloadTextlessComplete {
            get {
                return ResourceManager.GetString("downloadTextlessComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application could not be started. Please contact us..
        /// </summary>
        internal static string errorAdminRights {
            get {
                return ResourceManager.GetString("errorAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading.
        /// </summary>
        internal static string errorDownloadingFile {
            get {
                return ResourceManager.GetString("errorDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log in to server. Please check if a new version of the update program is available at http://www.pictogram.se/produkter/ ..
        /// </summary>
        internal static string errorDownloadNew {
            get {
                return ResourceManager.GetString("errorDownloadNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server. Please check username and password..
        /// </summary>
        internal static string errorLoginFailed {
            get {
                return ResourceManager.GetString("errorLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed due to file access error..
        /// </summary>
        internal static string failedFileAccess {
            get {
                return ResourceManager.GetString("failedFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed due to network problems..
        /// </summary>
        internal static string failedNetworkAccess {
            get {
                return ResourceManager.GetString("failedNetworkAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ini file updated..
        /// </summary>
        internal static string iniFileUpdated {
            get {
                return ResourceManager.GetString("iniFileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in plain text.
        /// </summary>
        internal static string inPlainText {
            get {
                return ResourceManager.GetString("inPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation has been aborted.
        /// </summary>
        internal static string installationAborted {
            get {
                return ResourceManager.GetString("installationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete..
        /// </summary>
        internal static string installationComplete {
            get {
                return ResourceManager.GetString("installationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for new images....
        /// </summary>
        internal static string lookingForNewImages {
            get {
                return ResourceManager.GetString("lookingForNewImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for new images without text....
        /// </summary>
        internal static string lookingForNewImagesWithoutText {
            get {
                return ResourceManager.GetString("lookingForNewImagesWithoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for new images with text....
        /// </summary>
        internal static string lookingForNewImagesWithText {
            get {
                return ResourceManager.GetString("lookingForNewImagesWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for new sounds....
        /// </summary>
        internal static string lookingForNewSounds {
            get {
                return ResourceManager.GetString("lookingForNewSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check account details!.
        /// </summary>
        internal static string mustCheckAccountDetails {
            get {
                return ResourceManager.GetString("mustCheckAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new files....
        /// </summary>
        internal static string newFiles {
            get {
                return ResourceManager.GetString("newFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new files to download..
        /// </summary>
        internal static string newFilesToDownload {
            get {
                return ResourceManager.GetString("newFilesToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text.
        /// </summary>
        internal static string noText {
            get {
                return ResourceManager.GetString("noText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictogramManager.
        /// </summary>
        internal static string pictogramManager {
            get {
                return ResourceManager.GetString("pictogramManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Pictogram Manager.
        /// </summary>
        internal static string restartPictogramManager {
            get {
                return ResourceManager.GetString("restartPictogramManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are.
        /// </summary>
        internal static string thereAre {
            get {
                return ResourceManager.GetString("thereAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating ini file....
        /// </summary>
        internal static string updatingIniFile {
            get {
                return ResourceManager.GetString("updatingIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictogram Manager is running. Remember to restart it to see the new images..
        /// </summary>
        internal static string warningPictogramManagerRunning {
            get {
                return ResourceManager.GetString("warningPictogramManagerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picto Online Update.
        /// </summary>
        internal static string webbHeader {
            get {
                return ResourceManager.GetString("webbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to without text.
        /// </summary>
        internal static string withoutText {
            get {
                return ResourceManager.GetString("withoutText", resourceCulture);
            }
        }
    }
}
